//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehinFlex.Models
{
    using System.ComponentModel.DataAnnotations; // Mansoure
    using MetadataClasses; //Mansoure
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(BonusesMetadata))] // Mansoure
    public partial class Bonuses
    {
        public int BonusId { get; set; }
        public int Bonus { get; set; }
        public Nullable<int> RefID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual RefCode RefCode { get; set; }
        public virtual Users Users { get; set; }
    }
}
