//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehinFlex.Models
{
    using System.ComponentModel.DataAnnotations; // Mansoure
    using MetadataClasses; //Mansoure
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(DiscountsMetadata))] // Mansoure
    public partial class Discounts
    {
        public int DiscountID { get; set; }
        
        public Nullable<int> ProductID { get; set; }
        
        public int DiscountPercent { get; set; }
       
    
        public virtual Products Products { get; set; }
        
    }
}
