//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehinFlex.Models
{
    using System.ComponentModel.DataAnnotations; // Mansoure
    using MetadataClasses; //Mansoure
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(ImagesMetadata))] // Mansoure
    public partial class Images
    {
        public int ImageID { get; set; }
        public string ImageTitle { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
