//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehinFlex.Models
{
    using System.ComponentModel.DataAnnotations; // Mansoure
    using MetadataClasses; //Mansoure
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(OrganizationChartMetadata))] // Mansoure
    public partial class OrganizationChart
    {
        public int OrgChartID { get; set; }
        public string OrgChartPost { get; set; }
        public string OrgChartFullName { get; set; }
        public string OrgChartPhone { get; set; }
        public string OrgChartEmail { get; set; }
        public string OrgChartTelegramID { get; set; }
    }
}
