//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehinFlex.Models
{
    using System.ComponentModel.DataAnnotations; // Mansoure
    using MetadataClasses; //Mansoure
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(RolesMetadata))] // Mansoure
    public partial class Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roles()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
