//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BehinFlex.Models
{
    using System.ComponentModel.DataAnnotations; // Mansoure
    using MetadataClasses; //Mansoure
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(VideosMetadata))] // Mansoure
    public partial class Videos
    {
        public int VideoID { get; set; }
        public string VideoTitle { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
